spring:
  datasource:
    url: jdbc:h2:mem:flightloggerdb
    driver-class-name: org.h2.Driver
    username: developer
    password:

  liquibase:
    change-log: classpath:db/changelog-master-dev.yaml

  h2:
    console:
      enabled: true
      path: /h2-console